# Generated by Django 2.2 on 2020-06-08 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('purpose', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], default='rent', max_length=30)),
                ('details', models.TextField()),
                ('images', models.ImageField(upload_to='pic')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
