# Generated by Django 2.2 on 2020-06-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Property',
        ),
    ]
