# Generated by Django 2.2 on 2020-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20200609_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='housing',
            field=models.CharField(choices=[('house', 'house'), ('apartment', 'apartment')], default='house', max_length=30),
        ),
    ]
